Update to latlong2
lpongetti/flutter_map_marker_cluster pull request #77
Opened 2021-06-05 21:33 UTC by Sipioteo

This is just a reference changes to make this compatible with the last Flutter_Map update

2021-06-11 03:17 UTC, klirix requested changes
There are some changes that might be out of scope.

Good job on update though :D

2021-06-11 03:17 UTC, klirix commented on example/ios/Flutter/flutter_export_environment.sh
> +export "FLUTTER_ROOT=E:\Programmi\Flutter"
is this needed in this pr?

2021-06-11 03:17 UTC, klirix commented on lib/src/marker_cluster_layer_options.dart
> -class PopupOptions {
This seems to be out of scope of this PR, maybe move it out into a separate one.

2021-06-11 03:17 UTC, klirix commented on lib/src/marker_cluster_layer.dart
> -    final PopupOptions popupOptions = widget.options.popupOptions;
Popups seem to be needed by cluster markers themselves

2021-06-21 08:01 UTC, TheOneWithTheBraid commented
It seems like this PR is obsolete with #69.

2021-06-21 10:21 UTC, closed without merging